import { useCallback, useEffect, useState } from 'react';
import { Check, Crown, RefreshCw, Shield, Wallet } from 'lucide-react';
import { apiService } from '../services/api';
import type { CampeonatoCriador, CriadorPerfil, PagamentoCriador } from '../services/api';
import { Spinner } from './Spinner';

interface Props { onAddToast: (type: 'success' | 'error' | 'warning' | 'info', title: string, desc?: string) => void; }
const brl = (v: number) => `R$ ${(v || 0).toFixed(2).replace('.', ',')}`;

export function AdminCriadores({ onAddToast }: Props) {
  const [criadores, setCriadores] = useState<CriadorPerfil[]>([]); const [eventos, setEventos] = useState<CampeonatoCriador[]>([]); const [pagamentos, setPagamentos] = useState<Record<number, PagamentoCriador[]>>({}); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const carregar = useCallback(async () => { setLoading(true); try { const [lista, eventosLista] = await Promise.all([apiService.adminCriadores(), apiService.adminEventosCriadores()]); setCriadores(lista); setEventos(eventosLista); const revisao = eventosLista.filter(evento => evento.status === 'pagamentos_pendentes'); const pares = await Promise.all(revisao.map(async evento => [evento.id, await apiService.pagamentosEventoCriador(evento.id)] as const)); setPagamentos(Object.fromEntries(pares)); } catch (erro: any) { onAddToast('error', 'Erro ao carregar', erro.message); } finally { setLoading(false); } }, [onAddToast]);
  useEffect(() => { carregar(); }, [carregar]);
  const executar = async (acao: () => Promise<any>, titulo: string) => { setBusy(true); try { const res = await acao(); onAddToast('success', titulo, res?.message); await carregar(); } catch (erro: any) { onAddToast('error', 'Erro', erro.message); } finally { setBusy(false); } };
  if (loading) return <div className="ff-card p-8 flex justify-center"><Spinner size="md" className="text-primary" /></div>;
  return <div className="space-y-5"><div className="ff-card p-5 flex justify-between gap-3"><div><p className="ff-kicker">Governança FlowFire</p><h2 className="text-xl font-black text-white">CRIADORES E COFRES</h2><p className="text-xs text-zinc-400 mt-1">Aprove perfis, revise eventos e libere valores manualmente.</p></div><button onClick={carregar} className="p-2 text-zinc-400 cursor-pointer"><RefreshCw className="w-4 h-4" /></button></div>
    <section className="ff-card p-5"><div className="flex items-center gap-2 mb-4"><Crown className="w-4 h-4 text-primary" /><h3 className="font-black text-white">Perfis de criador</h3></div><div className="space-y-2">{criadores.length ? criadores.map(criador => <div key={criador.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-zinc-800 bg-zinc-950/35 p-3"><div className="flex-1"><b className="block text-sm text-white">{criador.nick}</b><span className="text-[10px] text-zinc-500">@{criador.slug} · {criador.status}</span></div>{criador.status !== 'aprovado' && <button disabled={busy} onClick={() => executar(() => apiService.administrarCriador(criador.id!, 'aprovar'), 'Criador aprovado')} className="rounded-lg bg-emerald-500 px-3 py-2 text-xs font-bold text-zinc-950 cursor-pointer"><Check className="inline w-3.5 h-3.5 mr-1" />Aprovar</button>}{criador.status === 'aprovado' && <button disabled={busy} onClick={() => executar(() => apiService.administrarCriador(criador.id!, 'suspender'), 'Criador suspenso')} className="rounded-lg border border-rose-500/40 px-3 py-2 text-xs font-bold text-rose-400 cursor-pointer">Suspender</button>}</div>) : <p className="text-sm text-zinc-500">Nenhuma solicitação ainda.</p>}</div></section>
    <section className="space-y-3"><h3 className="text-sm font-black text-white flex items-center gap-2"><Shield className="w-4 h-4 text-primary" />Eventos em revisão e pagamentos</h3>{eventos.filter(evento => ['aguardando_revisao', 'pagamentos_pendentes'].includes(evento.status)).length ? eventos.filter(evento => ['aguardando_revisao', 'pagamentos_pendentes'].includes(evento.status)).map(evento => <article key={evento.id} className="ff-card p-5 space-y-3"><div className="flex flex-wrap justify-between gap-3"><div><span className="ff-kicker">@{evento.criador.slug}</span><h3 className="font-black text-white">{evento.nome}</h3><p className="text-xs text-zinc-400">Arrecadado {brl(evento.arrecadado)} · FlowFire retido {brl(evento.taxa_flowfire)} · Cofre {brl(evento.cofre_evento)}</p></div>{evento.status === 'aguardando_revisao' && <button disabled={busy} onClick={() => executar(() => apiService.apurarEventoCriador(evento.id), 'Prêmios calculados')} className="rounded-lg bg-amber-400 px-3 py-2 text-xs font-bold text-zinc-950 cursor-pointer">Aprovar placar</button>}</div>{(pagamentos[evento.id] ?? []).map(pagamento => <div key={pagamento.id} className="flex items-center gap-3 rounded-lg border border-zinc-800 bg-zinc-950/35 p-3 text-xs"><Wallet className="w-4 h-4 text-emerald-400" /><span className="flex-1 text-white"><b>{pagamento.nick}</b> · {pagamento.tipo === 'criador' ? 'parte do criador' : `${pagamento.colocacao}º prêmio`}</span><b className="text-emerald-400">{brl(pagamento.valor)}</b><button disabled={busy || pagamento.status !== 'pendente'} onClick={() => executar(() => apiService.liberarPagamentoCriador(pagamento.id), 'Pagamento liberado')} className="rounded-lg bg-emerald-500 px-2.5 py-1.5 font-bold text-zinc-950 cursor-pointer">Liberar</button></div>)}</article>) : <div className="ff-card p-6 text-sm text-zinc-500">Nenhum evento de criador aguardando ação.</div>}</section>
  </div>;
}
